steps:
  # Install Node.js and build the app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    id: 'npm-install'

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'npm-build'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=https://ftjukgofugzoxhvqhrez.supabase.co'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0anVrZ29mdWd6b3hodnFocmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NjQyMDksImV4cCI6MjA3NzI0MDIwOX0.j8kwtLaklvEB59X4_ir3HBGGkUmXfFbnl4M8lFC8wZM'
      - '-t'
      - 'gcr.io/$PROJECT_ID/invoiceapp:latest'
      - '.'
    id: 'build-container'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/invoiceapp:latest']
    id: 'push-container'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'invoiceapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/invoiceapp:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--set-env-vars=VITE_SUPABASE_URL=https://ftjukgofugzoxhvqhrez.supabase.co'
      - '--set-env-vars=VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0anVrZ29mdWd6b3hodnFocmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NjQyMDksImV4cCI6MjA3NzI0MDIwOX0.j8kwtLaklvEB59X4_ir3HBGGkUmXfFbnl4M8lFC8wZM'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'
      - '--concurrency=80'
      - '--max-instances=3'
      - '--min-instances=0'
    id: 'deploy'

images:
  - 'gcr.io/$PROJECT_ID/invoiceapp:latest'
